---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: grafana-http
  namespace: metrics

spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`grafana.agrrh.com`)
      middlewares:
        - name: whitelist
          namespace: kube-system
      services:
        - kind: Service
          name: grafana-operated
          namespace: metrics
          port: 80
