---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: config
  namespace: tg-dukhota-bot
spec:
  encryptedData:
    tg_token: AgCh0sDAAvi+KV/sVmf9RB/bhpSkJWo/+rJKj/T44qIXzhCO4UGSa6UDbPVDYrhgJpgJ6BmX1vgjUugb7WFXTPw65s4N3swCp7LguMF5gC8ymJ/RtWY3me22VPhMnpKDfwlV7B+DGOgH3J04N2/3ntcV86IKqRNfujmKH187wB0EH/+H7WhgxxsA2l5ihBQAzecZznlrOPVAzWF4rE9MJapq2YPNbO9YccVoRg1Nyaobg9sn187Z7zxzGO48FNU6vMnCN4WsMFaUbUWBEN6wxODaZ6eA9CwANjMauo/be+uCBrygQcntw1M9L8G8Kv4t1FOb9CO2XreB8AtPVIkRA5pdW1PUXLdijwx6IEGEydnVcdpr9KYuZm/w5gC2zxfQaeFYfUqvRye4vXemZzdJK2pKcCVdShhrU6au1dhx5U+qoBbQnGl8Z9hhKmJnbujAtPyYvUHyzDPgIhOpa21r0IpJI6Pmwf/jBGAD/+rlBp/jeuGyOLV77rxqAoU+L+aRAU3wwrLdDvGGtdPlip+7Ttyp/7phDOCMzFBzhRasvZED7crdw3oP/X35OdcAfacU9Om8w86jjCkvSirAOV48g1cXd1MmvMJ8eFDDRsfAXZXY3di88Sil+LyJA3szddsTD4eAjMtr4eI568qhjZ2EUR5cTZYY7UshY48e91Mu63XnkiCF+2Tc2paLE06MvpGWevkBcchcA5KqmGaPV1jJj9WlblRqGJ87qKM6oDh85j3HsOXqB7tOH+GXyTl7VSyj
  template:
    metadata:
      creationTimestamp: null
      name: config
      namespace: tg-dukhota-bot
