---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: app-homer
  namespace: argocd

spec:
  project: personal

  destination:
    name: funny-bell
    namespace: argocd

  source:
    repoURL: https://github.com/agrrh/infrastructure
    targetRevision: HEAD
    path: kubernetes/personal/applications/homer
    directory:
      recurse: true

  syncPolicy:
    automated:
      selfHeal: true
      prune: false
