---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: unleash
  namespace: argocd

spec:
  project: tech

  destination:
    name: funny-bell
    namespace: unleash

  source:
    # repoURL: https://github.com/Unleash/helm-charts.git
    # targetRevision: unleash-5.4.3
    # path: charts/unleash

    repoURL: https://docs.getunleash.io/helm-charts
    chart: unleash
    targetRevision: '5.4.3'

    helm:
      releaseName: unleash
      values: |
        # https://github.com/Unleash/helm-charts/blob/unleash-5.4.3/charts/unleash/values.yaml
        replicaCount: 1

      # TODO: Secure default DB secrets

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
