---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rclone
  namespace: backups
spec:
  encryptedData:
    RCLONE_CONFIG_CONTENT: AgC+7DIm/zalWiL2Fs6inZojUMTDYcADQWLMoGEIlhsCH4BsXs7Z8xJQjidB7kNQKYGgQf6kbjBfXX858Q4IBdkQRK/CFQTEa84zWrtdAjnzrrs6T3KP0fkde97+mywptpGvYV4uEp+uRz77LRCDuM78XYx4bsK1w4ZDlW0eWjpaUGeXF0G19odhB+3Hz5R0PdzIN483xj9T/HZMuICIkUspVivUoqDSU/CX7UPeQV/KTgeyvsaIEx3rZghmQzUK39s2pbNdArF3Njk52z7h68DKYOZJwnpebOovfQGzKVOYhGrlCHPolZhSQ98EXZlmS4/WAR55pzEZXDRv45gBmozbNNXbk8fbj1Y54r1SUkb2+HmSXJefkDmedLuKWAB4V+ALwP31OHpL2O8uRA+pZhR0zboH52qog/mbynjpmI38sK/zyFT6sowyPo5WtUHExqIxc4YE71Vm6lPkAx0etdTztl3w86oyrfUTxnmbgfWr5bxWCpc0tfCE++NUGfNMkpnPIhNEC4FfblaTcyvqvsZ1d7sS2CHfAtso6r1xtY4QRnUrpub/grwuWj1Y8kgv6A6dvhsXK5q3XjV3d+qvpl7imqOFAzqglfN1skLjD/NLwUNV/eu7oQ3/YRuuoANHnldo8OBRiTybEQvCO8xF3tRJIcKPESXSVCPbj1DnhDUewgSTlHS11IuGA8pCTjvW/yMteIViO2EbzMAB1/TNna+YJ6sqfy/55DpJ2Mx0Ns6Kte4TMxuJARY85usTQ5s9i07VWVImsnwuzp5X8MSIW9CEs6LAu0jEcrUbLS85uvMoxrwxzXoAT8e4nURtZHG38zIUyc/dFxLD2cGE8lxbt1cgKr/BD/IbAWFgMe58zZaUFJVMJ2lvuF3PrY4Ry3ONshEymRRmNHc5FafVJZJUhQK0rv8m9HKSDeY1Qb+ncQbXXb5yiXILtx7zQbDT6MoZKJIVWxX0nYeVmh2Yyz5OoT2WK7+CJGQhbXegTlafgQYHR7RoyJsMVyQZSlN9+t7lknoOj/jgaWfc0zF9NhDrdJ7X7iy0x3W4FxaTpRnlxmSIwKqggRSrO3btP+OFtkCvnWBQ+bGbaefyjMUK/X7XE/3HWLpMNuEZQSNjJMT8/VUgmixzqquUaSwvs0gg7EZEE0cWkPb38br8ejNvDsdGTsZRaOcs7ZPQ9BBd+k2/arLExOOcew==
  template:
    metadata:
      creationTimestamp: null
      name: rclone
      namespace: backups
