---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: kargo-http
  namespace: kargo

spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`kargo.agrrh.com`)
      middlewares:
        - name: whitelist
          namespace: kube-system
      services:
        - kind: Service
          name: kargo-api
          namespace: kargo
          port: 80

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: kargo-external-webhooks-http
  namespace: kargo

spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`kargo-webhook.agrrh.com`)
      middlewares: []
      services:
        - kind: Service
          name: kargo-external-webhooks-server
          namespace: kargo
          port: 80
