---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: kargo-http
  namespace: kargo

spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`kargo.agrrh.com`)
      middlewares:
        - name: whitelist
          namespace: kube-system
      services:
        - kind: Service
          name: kargo-api
          namespace: kargo
          port: 443
          scheme: https
          passHostHeader: true
