---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: apps-personal
  namespace: argocd

spec:
  project: default

  destination:
    name: funny-bell
    namespace: argocd

  source:
    repoURL: https://github.com/agrrh/infrastructure
    targetRevision: HEAD
    path: kubernetes/personal

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
