---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: app-sealed-secrets
  namespace: argocd

spec:
  project: tech

  destination:
    name: funny-bell
    namespace: argocd

  source:
    repoURL: https://github.com/agrrh/infrastructure
    targetRevision: HEAD
    path: kubernetes/tech/applications/sealed-secrets
    directory:
      recurse: true

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
