---

apiVersion: v1
kind: ConfigMap

metadata:
  name: redis
  namespace: n8n

data:
  redis.conf: |
    databases 8
    maxclients 1000
    timeout 30
    port 6379
    tcp-keepalive 300
    logfile ""
    lazyfree-lazy-eviction no
    lazyfree-lazy-expire no
    lazyfree-lazy-server-del no
