---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: authelia
  namespace: authelia

spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      enableServiceLinks: false
      containers:
        - name: main
          image: authelia/authelia:4.39.14
          env:
            - name: TZ
              value: Europe/Moscow
          command: ["authelia"]
          args:
            - --config=/config/configuration.yml
            - --config=/config/oidc.yml
              
          ports:
            - name: http
              containerPort: 9091

          volumeMounts:
            - name: data
              mountPath: /var/lib/authelia
            - name: config
              mountPath: /config/configuration.yml
              subPath: configuration.yml
            - name: config
              mountPath: /config/users.yml
              subPath: users.yml
            - name: config
              mountPath: /config/oidc.yml
              subPath: oidc.yml

      volumes:
        - name: config
          secret:
            secretName: config
            items:
              - key: configuration.yml
                path: configuration.yml
              - key: users.yml
                path: users.yml
              - key: oidc.yml
                path: oidc.yml
        - name: data
          persistentVolumeClaim:
            claimName: authelia-data
