---
apiVersion: v1
kind: Service

metadata:
  name: vector-syslog
  namespace: vector
  labels:
    app: vector

spec:
  type: NodePort
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  selector:
    app: vector
  ports:
    - nodePort: 30900
      port: 9000
      protocol: TCP
      targetPort: 9000
    - nodePort: 30900
      port: 9000
      protocol: UDP
      targetPort: 9000
