---
apiVersion: v1
kind: Service

metadata:
  name: goflow
  namespace: netflow
  labels:
    app: goflow

spec:
  type: NodePort
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  selector:
    app: goflow
  ports:
    - nodePort: 32055
      port: 2055
      protocol: UDP
      targetPort: 2055
