---

apiVersion: v1
kind: Service
metadata:
  name: dockerhub-proxy
  namespace: dockerhub-proxy
  labels:
    app: dockerhub-proxy
spec:
  selector:
    app: dockerhub-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
