---

# NOTE: https://artifacthub.io/packages/helm/bitnami/mariadb

kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: passbolt-mariadb
  namespace: argocd
spec:
  project: personal

  destination:
    name: funny-bell
    namespace: passbolt

  source:
    repoURL: https://github.com/agrrh/infrastructure
    targetRevision: HEAD
    path: charts/mariadb
    
    helm:
      releaseName: mariadb
      values: |
        image:
          repository: bitnamilegacy/mariadb
          tag: 10.6.12-debian-11-r3

        auth:
          existingSecret: passbolt-mariadb

        primary:
          extraEnvVarsSecret: passbolt-mariadb-env

          persistence:
            storageClass: local-path
            size: 5Gi
            accessModes:
              - ReadWriteOnce

          tolerations:
            - effect: NoSchedule
              key: agrrh.com/node-role
              operator: Equal
              value: master

  syncPolicy:
    # syncOptions:
    #   - CreateNamespace=true
    automated:
      selfHeal: true
      prune: false
