---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: passbolt-http
  namespace: passbolt
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`passbolt.agrrh.com`)
      middlewares:
        - name: whitelist
          namespace: kube-system
      services:
        - kind: Service
          name: passbolt
          namespace: passbolt
          port: 80
