---

kind: Application
apiVersion: argoproj.io/v1alpha1

metadata:
  name: bus
  namespace: argocd

spec:
  project: tech

  destination:
    name: funny-bell
    namespace: bus

  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts
    chart: nats
    targetRevision: 2.12.3

    helm:
      values: |
        # https://github.com/nats-io/k8s/blob/nats-2.12.3/helm/charts/nats/values.yaml
        fullnameOverride: "nats"
        config:
          jetstream:
            enabled: true

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
